// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// We load .env.local first (Next.js convention for local dev secrets) and then
// .env, so the Prisma CLI sees the same DATABASE_URL the Next.js app does.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. Prefer DIRECT_URL
    // when set; fall back to DATABASE_URL for local-only setups.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
